apiVersion: v1
kind: Pod
metadata:
  name: ceph
  namespace: openstack
  labels:
    app.kubernetes.io/name: ceph
spec:
  hostNetwork: true
  containers:
   - image: quay.io/ceph/daemon:latest-quincy
     name: ceph
     env:
     - name: MON_IP
       value: "192.168.130.11"
     - name: CEPH_DAEMON
       value: demo
     - name: CEPH_PUBLIC_NETWORK
       value: "0.0.0.0/0"
     - name: DEMO_DAEMONS
       value: "osd"
     volumeMounts:
      - mountPath: /var/lib/ceph
        name: data
      - mountPath: /var/log/ceph
        name: log
      - mountPath: /run/ceph
        name: run
  volumes:
  - name: data
    emptyDir:
      sizeLimit: 500Mi
  - name: run
    emptyDir:
      sizeLimit: 500Mi
  - name: log
    emptyDir:
      sizeLimit: 500Mi
  securityContext:
    privileged: true
    allowPrivilegeEscalation: true
    runAsUser: 0
