apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ceph-pod.yaml
namespace: openstack
patches:
- patch: |-
    - op: replace
      path: /spec
      value:
       containers:
         - image: quay.io/ceph/ceph:v17
    #- op: replace
    #  path: /spec/containers/env/MON_IP
    #  value: 192.168.130.11
  target:
    kind: Pod
