apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: horizon-theme
  namespace: openstack
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
