apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  secret: osp-secret
  storageClass: local-storage
  keystone:
    template:
      containerImage: quay.io/tripleozedcentos9/openstack-keystone:current-tripleo
      databaseInstance: openstack
      secret: osp-secret
  mariadb:
    templates:
      openstack:
        containerImage: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo
        storageRequest: 500M
        storageClass: local-storage
  rabbitmq:
    templates:
      rabbitmq:
        replicas: 1
      rabbitmq-cell1:
        replicas: 1
  memcached:
    templates:
      memcached:
        replicas: 1
  glance:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
      storageClass: ""
      storageRequest: 10G
      glanceAPIInternal:
        containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
      glanceAPIExternal:
        containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
  cinder:
    template:
      cinderAPI:
        replicas: 0
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-api:current-tripleo
      cinderScheduler:
        replicas: 0
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-scheduler:current-tripleo
      cinderBackup:
        replicas: 0
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-backup:current-tripleo
      cinderVolumes:
        volume1:
          containerImage: quay.io/tripleozedcentos9/openstack-cinder-volume:current-tripleo
          replicas: 0
  manila:
    enabled: true
    template:
      manilaAPI:
        customServiceConfig: |
          [DEFAULT]
          debug = true
          enabled_share_protocols=nfs,cephfs,cifs
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-manila-api:current-tripleo
      manilaScheduler:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-manila-scheduler:current-tripleo
      manilaShares:
        share1:
          customServiceConfig: |
              [DEFAULT]
              enabled_share_backends=cephfsnfs
              [cephfsnfs]
              driver_handles_share_servers=False
              share_backend_name=cephfs
              share_driver=manila.share.drivers.cephfs.driver.CephFSDriver
              cephfs_auth_id=openstack
              cephfs_cluster_name=ceph
              cephfs_nfs_cluster_id=cephfs
              cephfs_protocol_helper_type=NFS
          containerImage: quay.io/tripleozedcentos9/openstack-manila-share:current-tripleo
          replicas: 1
        share2:
          customServiceConfig: |
              [DEFAULT]
              enabled_share_backends=cephfs
              [cephfs]
              driver_handles_share_servers=False
              share_backend_name=cephfs
              share_driver=manila.share.drivers.cephfs.driver.CephFSDriver
              cephfs_conf_path=/etc/ceph/ceph.conf
              cephfs_auth_id=openstack
              cephfs_cluster_name=ceph
              cephfs_enable_snapshots=True
              cephfs_ganesha_server_is_remote=False
              cephfs_volume_mode=0755
              cephfs_protocol_helper_type=CEPHFS
          containerImage: quay.io/tripleozedcentos9/openstack-manila-share:current-tripleo
          replicas: 1
        share3:
          customServiceConfig: |
            [DEFAULT]
            debug = true
            enabled_share_backends=netapp
            [netapp]
            driver_handles_share_servers=False
            share_backend_name=netapp
            share_driver=manila.share.drivers.netapp.common.NetAppDriver
            netapp_storage_family=ontap_cluster
            netapp_transport_type=http
          customServiceConfigSecrets:
            - osp-secret-manila-netapp
          containerImage: quay.io/tripleozedcentos9/openstack-manila-share:current-tripleo
          replicas: 1

      extraMounts:
        - name: v1
          region: r1
          extraVol:
            - propagation:
              - Manila
              - Glance
              - Cinder
              extraVolType: Ceph
              volumes:
              - name: ceph
                projected:
                  sources:
                  - secret:
                      name: ceph-conf-files
              mounts:
              - name: ceph
                mountPath: "/etc/ceph"
                readOnly: true
  ovn:
    template:
      ovnDBCluster:
        ovndbcluster-nb:
          replicas: 0
          containerImage: quay.io/tripleozedcentos9/openstack-ovn-nb-db-server:current-tripleo
          dbType: NB
          storageRequest: 10G
        ovndbcluster-sb:
          replicas: 0
          containerImage: quay.io/tripleozedcentos9/openstack-ovn-sb-db-server:current-tripleo
          dbType: SB
          storageRequest: 10G
      ovnNorthd:
        replicas: 0
        containerImage: quay.io/tripleozedcentos9/openstack-ovn-northd:current-tripleo
      ovnController:
        external-ids:
          system-id: "random"
          ovn-bridge: "br-int"
          ovn-encap-type: "geneve"

  ovs:
    template:
      ovsContainerImage: "quay.io/skaplons/ovs:latest"
      ovnContainerImage: "quay.io/tripleozedcentos9/openstack-ovn-controller:current-tripleo"
      external-ids:
        system-id: "random"
        ovn-bridge: "br-int"
        ovn-encap-type: "geneve"
  neutron:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-neutron-server:current-tripleo
      secret: osp-secret
  nova:
    enabled: false
    template:
      secret: osp-secret
  ironic:
    template:
      databaseInstance: openstack
      ironicAPI:
        replicas: 0
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-api:current-tripleo
      ironicConductors:
      - replicas: 0
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-conductor:current-tripleo
        pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
        storageRequest: 10G
      ironicInspector:
        replicas: 0
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-inspector:current-tripleo
        pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
      secret: osp-secret
  extraMounts:
    - name: v1
      region: r1
      extraVol:
        - propagation:
          - Manila
          - Glance
          - Cinder
          extraVolType: Ceph
          volumes:
          - name: ceph
            projected:
              sources:
              - secret:
                  name: ceph-conf-files
          mounts:
          - name: ceph
            mountPath: "/etc/ceph"
            readOnly: true
