apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ceph-pod.yaml
namespace: openstack
patches:
- patch: |-
    - op: replace
      path: /spec/containers/0/image
      value:
       containers:
         - image: quay.io/ceph/ceph:v18
    - op: replace
      path: /metadata/namespace
      value: $NAMESPACE
    - op: replace
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1networks
      value: $NETWORKS_ANNOTATION
  target:
    kind: Pod
