apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  secret: osp-secret
  storageClass: local-storage
  keystone:
    template:
      containerImage: quay.io/tripleozedcentos9/openstack-keystone:current-tripleo
      databaseInstance: openstack
      secret: osp-secret
  mariadb:
    templates:
      openstack:
        containerImage: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo
        storageRequest: 500M
      openstack-cell1:
        containerImage: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo
        storageRequest: 500M
  galera:
    enabled: false
    templates:
      openstack:
        containerImage: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo
        storageClass: local-storage
        storageRequest: 500M
        secret: osp-secret
        replicas: 1
      openstack-cell1:
        containerImage: quay.io/tripleozedcentos9/openstack-mariadb:current-tripleo
        storageClass: local-storage
        storageRequest: 500M
        secret: osp-secret
        replicas: 1
  rabbitmq:
    templates:
      rabbitmq:
        replicas: 1
        #resources:
        #  requests:
        #    cpu: 500m
        #    memory: 1Gi
        #  limits:
        #    cpu: 800m
        #    memory: 1Gi
      rabbitmq-cell1:
        replicas: 1
  memcached:
    enabled: false
    templates:
      memcached:
        containerImage: quay.io/tripleozedcentos9/openstack-memcached:current-tripleo
        replicas: 1
  placement:
    enabled: false
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-placement-api:current-tripleo
      secret: osp-secret
  glance:
    enabled: false
    template:
      customServiceConfigSecrets:
        - glance-secret
        - glance-secret2
      customServiceConfig: |
        [DEFAULT]
        enabled_backends=default_backend:rbd
        [glance_store]
        default_backend=default_backend
        [default_backend]
        rbd_store_ceph_conf=/etc/ceph/ceph.conf
        rbd_store_user=openstack
        rbd_store_pool=images
        store_description=Ceph glance store backend.
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
      storageClass: ""
      storageRequest: 10G
      glanceAPIInternal:
        containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
        replicas: 2
      glanceAPIExternal:
        containerImage: quay.io/tripleozedcentos9/openstack-glance-api:current-tripleo
  cinder:
    enabled: false
    template:
      databaseInstance: openstack
      secret: osp-secret
      cinderAPI:
        replicas: 0
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-api:current-tripleo
      cinderScheduler:
        replicas: 0
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-scheduler:current-tripleo
      cinderBackup:
        replicas: 0 # backend needs to be configured
        containerImage: quay.io/tripleozedcentos9/openstack-cinder-backup:current-tripleo
      cinderVolumes:
        volume1:
          containerImage: quay.io/tripleozedcentos9/openstack-cinder-volume:current-tripleo
          replicas: 0 # backend needs to be configured
  manila:
    enabled: true
    template:
      customServiceConfig: |
         [DEFAULT]
         debug = true
         enabled_share_backends=cephfs
         enabled_share_protocols=cephfs
         [cephfs]
         driver_handles_share_servers=False
         share_backend_name=cephfs
         share_driver=manila.share.drivers.cephfs.driver.CephFSDriver
         cephfs_conf_path=/etc/ceph/ceph.conf
         cephfs_auth_id=openstack
         cephfs_cluster_name=ceph
         cephfs_enable_snapshots=True
         cephfs_ganesha_server_is_remote=False
         cephfs_volume_mode=0755
         cephfs_protocol_helper_type=CEPHFS
      manilaAPI:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-manila-api:current-tripleo
      manilaScheduler:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-manila-scheduler:current-tripleo
      manilaShares:
        share1:
          customServiceConfig: |
            [DEFAULT]
            transport_url=rabbit://openstack:redhat@10.217.4.183:5672
            debug = true
            enabled_share_backends=cephfs
            enabled_share_protocols=cephfs
            [cephfs]
            driver_handles_share_servers=False
            share_backend_name=cephfs
            share_driver=manila.share.drivers.cephfs.driver.CephFSDriver
            cephfs_conf_path=/etc/ceph/ceph.conf
            cephfs_auth_id=openstack
            cephfs_cluster_name=ceph
            cephfs_enable_snapshots=True
            cephfs_ganesha_server_is_remote=False
            cephfs_volume_mode=0755
            cephfs_protocol_helper_type=CEPHFS
          containerImage: quay.io/tripleozedcentos9/openstack-manila-share:current-tripleo
          replicas: 1
  ovn:
    template:
      ovnDBCluster:
        ovndbcluster-nb:
          replicas: 1
          containerImage: quay.io/tripleozedcentos9/openstack-ovn-nb-db-server:current-tripleo
          dbType: NB
          storageRequest: 10G
        ovndbcluster-sb:
          replicas: 1
          containerImage: quay.io/tripleozedcentos9/openstack-ovn-sb-db-server:current-tripleo
          dbType: SB
          storageRequest: 10G
      ovnNorthd:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ovn-northd:current-tripleo
  ovs:
    template:
      ovsContainerImage: "quay.io/skaplons/ovs:latest"
      ovnContainerImage: "quay.io/tripleozedcentos9/openstack-ovn-controller:current-tripleo"
      external-ids:
        system-id: "random"
        ovn-bridge: "br-int"
        ovn-encap-type: "geneve"
  neutron:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleozedcentos9/openstack-neutron-server:current-tripleo
      secret: osp-secret
      customServiceConfigSecrets:
        - neutron-secret
  nova:
    enabled: false
    template:
      secret: osp-secret
  ironic:
    enabled: false
    template:
      databaseInstance: openstack
      ironicAPI:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-api:current-tripleo
      ironicConductors:
      - replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-conductor:current-tripleo
        pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
        storageRequest: 10G
      ironicInspector:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-ironic-inspector:current-tripleo
        pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
      secret: osp-secret
  extraMounts:
    - name: v1
      region: r1
      extraVol:
        - propagation:
          - Manila
          extraVolType: Ceph
          volumes:
          - name: ceph
            projected:
              sources:
              - secret:
                  name: ceph-conf-files
          mounts:
          - name: ceph
            mountPath: "/etc/ceph"
            readOnly: true
