apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  secret: osp-secret
  storageClass: local-storage
  keystone:
    template:
      containerImage: quay.io/tripleowallabycentos9/openstack-keystone:current-tripleo
      databaseInstance: openstack
      secret: osp-secret
  mariadb:
    template:
      containerImage: quay.io/tripleowallabycentos9/openstack-mariadb:current-tripleo
      storageRequest: 500M
  rabbitmq:
    template:
      replicas: 1
      #resources:
      #  requests:
      #    cpu: 500m
      #    memory: 1Gi
      #  limits:
      #    cpu: 800m
      #    memory: 1Gi
  placement:
    template:
      containerImage: quay.io/tripleowallabycentos9/openstack-placement-api:current-tripleo
  glance:
    template:
      databaseInstance: openstack
      containerImage: quay.io/tripleowallabycentos9/openstack-glance-api:current-tripleo
      storageClass: local-storage
      storageRequest: 1G
      glanceAPIInternal:
        containerImage: quay.io/tripleowallabycentos9/openstack-glance-api:current-tripleo
      glanceAPIExternal:
        containerImage: quay.io/tripleowallabycentos9/openstack-glance-api:current-tripleo
  cinder:
    template:
      cinderAPI:
        replicas: 1
        containerImage: quay.io/tripleowallabycentos9/openstack-cinder-api:current-tripleo
      cinderScheduler:
        replicas: 1
        containerImage: quay.io/tripleowallabycentos9/openstack-cinder-scheduler:current-tripleo
      cinderBackup:
        replicas: 1
        containerImage: quay.io/tripleowallabycentos9/openstack-cinder-backup:current-tripleo
        customServiceConfig: |
          [DEFAULT]
          backup_driver = cinder.backup.drivers.ceph.CephBackupDriver
          backup_ceph_pool = backups
          backup_ceph_user = admin
      cinderVolumes:
        volume1:
          containerImage: quay.io/tripleowallabycentos9/openstack-cinder-volume:current-tripleo
          replicas: 1
          customServiceConfig: |
            [DEFAULT]
            enabled_backends=ceph
            [ceph]
            volume_backend_name=ceph
            volume_driver=cinder.volume.drivers.rbd.RBDDriver
            rbd_ceph_conf=/etc/ceph/ceph.conf
            rbd_user=<USER>
            rbd_pool=<POOL>
            rbd_flatten_volume_from_snapshot=False
            rbd_secret_uuid=<UUID>
  extraMounts:
    - name: v1
      region: r1
      extraVol:
      - propagation:
        - Glance
        - volume1
        - Compute
        - CinderBackup
        extraVolType: Ceph
        volumes:
        - name: ceph
          projected:
            sources:
            - secret:
                name: ceph-client-conf
            - secret:
                name: ceph-client-conf2
        mounts:
        - name: ceph
          mountPath: "/etc/ceph"
          readOnly: true
      - propagation:
        - Compute
        - CinderScheduler
        - Glance
        extraVolType: Ceph
        volumes:
        - name: ceph2
          projected:
            sources:
            - secret:
                name: ceph-client-conf
        mounts:
        - name: ceph2
          mountPath: "/etc/ceph2"
          readOnly: true
