apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  serviceUser: glance
  containerImage: quay.io/tripleowallabycentos9/openstack-glance-api:current-tripleo
  customServiceConfig: |
    [DEFAULT]
    debug = true
    # todo: add custom glance config for ceph
  databaseInstance: openstack
  databaseUser: glance
  glanceAPIInternal:
    debug:
      service: false
    preserveJobs: false
    replicas: 1
  glanceAPIExternal:
    debug:
      service: false
    preserveJobs: false
    replicas: 1
  secret: osp-secret
  storageClass: local-storage
  storageRequest: 1G
  extraMounts:
    - name: v1
      region: r1
      extraVol:
        - propagation:
          - Cinder
          - Compute
          extraVolType: Ceph
          volumes:
          - name: ceph
            projected:
              sources:
              - secret:
                  name: ceph-client-conf
              - secret:
                  name: ceph-client-conf2
          mounts:
          - name: ceph
            mountPath: "/etc/ceph"
            readOnly: true
        - propagation:
          - Glance
          - Compute
          extraVolType: Ceph
          volumes:
          - name: ceph2
            projected:
              sources:
              - secret:
                  name: ceph-client-conf
          mounts:
          - name: ceph2
            mountPath: "/etc/ceph2"
            readOnly: true
