apiVersion: manila.***REMOVED***.org/v1beta1
kind: Manila
metadata:
  name: manila
  namespace: ***REMOVED***
spec:
  serviceUser: manila
  customServiceConfig: |
    [DEFAULT]
    debug = true
    transport_url=rabbit://***REMOVED***:***REMOVED***@rabbitmq.***REMOVED***.svc:5672
  databaseInstance: ***REMOVED***
  secret: osp-secret
  databaseUser: manila
  manilaAPI:
    replicas: 1
    containerImage: quay.io/tripleowallabycentos9/***REMOVED***-manila-api:current-tripleo
  manilaScheduler:
    replicas: 1
    containerImage: quay.io/tripleowallabycentos9/***REMOVED***-manila-scheduler:current-tripleo
  manilaShares:
    share1:
      containerImage: quay.io/tripleowallabycentos9/***REMOVED***-manila-share:current-tripleo
      replicas: 1
    share2:
      containerImage: quay.io/tripleowallabycentos9/***REMOVED***-manila-share:current-tripleo
      replicas: 1
